//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDMultiStash.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDMultiStash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallDown {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallOver {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallUp {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///err_gamedir_not_found = Spielverzeichnis nicht gefunden!
        ///err_docsdir_not_found = Dokumentenverzeichnis nicht gefunden!
        ///err_gd_already_running = Grim Dawn läuft bereits!
        ///err_invalid_transfer_file = Ungültige Transfer-Datei!
        ///err_no_stash_selected = Kein Stash ausgewählt!
        ///err_cannot_delete_stash = Stash &quot;{0}&quot; kann nicht gelöscht werden: {1}
        ///err_stash_is_active = Stash ist gerade aktiv
        ///
        ///window_setup = Einstellungen
        ///window_create_stash = Stash erstellen
        ///window_import_stash = Stash importieren
        ///
        ///setu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string de_Deutsch {
            get {
                return ResourceManager.GetString("de_Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///err_gamedir_not_found = Game directory not found!
        ///err_docsdir_not_found = Documents directory not found!
        ///err_gd_already_running = Grim Dawn is already running!
        ///err_invalid_transfer_file = Invalid transfer file!
        ///err_no_stash_selected = No stash selected!
        ///err_cannot_delete_stash = Stash &quot;{0}&quot; can not be deleted: {1}
        ///err_stash_is_active = Stash is currently active
        ///
        ///window_setup = Setup
        ///window_create_stash = Create Stash
        ///window_import_stash = Import Stash
        ///
        ///setup_tab_common = Common
        ///setup_tab_beha [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string en_English {
            get {
                return ResourceManager.GetString("en_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon icon32 {
            get {
                object obj = ResourceManager.GetObject("icon32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die records/creatures/npcs/npcgear/npc_child_girl_hair01:4
        ///records/creatures/npcs/npcgear/npc_child_girl_hair02:4
        ///records/creatures/npcs/npcgear/npc_child_girl_hair03:4
        ///records/creatures/npcs/npcgear/npc_child_girl_hat01:4
        ///records/creatures/npcs/npcgear/npc_feet_blacklegion01:4
        ///records/creatures/npcs/npcgear/npc_feet_blacklegion02:4
        ///records/creatures/npcs/npcgear/npc_feet_exile01:4
        ///records/creatures/npcs/npcgear/npc_feet_necromancer01:4
        ///records/creatures/npcs/npcgear/npc_feet_necromancer02:4
        ///records/cr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string itemsizes {
            get {
                return ResourceManager.GetString("itemsizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] LinBiolinum_RB {
            get {
                object obj = ResourceManager.GetObject("LinBiolinum_RB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio0 {
            get {
                object obj = ResourceManager.GetObject("radio0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio1 {
            get {
                object obj = ResourceManager.GetObject("radio1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollBarInner {
            get {
                object obj = ResourceManager.GetObject("ScrollBarInner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
