//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDMultiStash.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDMultiStash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseGray {
            get {
                object obj = ResourceManager.GetObject("buttonCloseGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseWhite {
            get {
                object obj = ResourceManager.GetObject("buttonCloseWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDropDownArrow {
            get {
                object obj = ResourceManager.GetObject("ButtonDropDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDropUpArrow {
            get {
                object obj = ResourceManager.GetObject("ButtonDropUpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLargeDown {
            get {
                object obj = ResourceManager.GetObject("ButtonLargeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLargeOver {
            get {
                object obj = ResourceManager.GetObject("ButtonLargeOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLargeUp {
            get {
                object obj = ResourceManager.GetObject("ButtonLargeUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonMinimizeGray {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonMinimizeWhite {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRoundDown {
            get {
                object obj = ResourceManager.GetObject("ButtonRoundDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRoundDownOver {
            get {
                object obj = ResourceManager.GetObject("ButtonRoundDownOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRoundOver {
            get {
                object obj = ResourceManager.GetObject("ButtonRoundOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRoundUp {
            get {
                object obj = ResourceManager.GetObject("ButtonRoundUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallDown {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallOver {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallUp {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonTrayGray {
            get {
                object obj = ResourceManager.GetObject("buttonTrayGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonTrayWhite {
            get {
                object obj = ResourceManager.GetObject("buttonTrayWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow10x18 {
            get {
                object obj = ResourceManager.GetObject("caravanWindow10x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow10x18add {
            get {
                object obj = ResourceManager.GetObject("caravanWindow10x18add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow10x18hover {
            get {
                object obj = ResourceManager.GetObject("caravanWindow10x18hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow8x16 {
            get {
                object obj = ResourceManager.GetObject("caravanWindow8x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow8x16add {
            get {
                object obj = ResourceManager.GetObject("caravanWindow8x16add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caravanWindow8x16hover {
            get {
                object obj = ResourceManager.GetObject("caravanWindow8x16hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxBack {
            get {
                object obj = ResourceManager.GetObject("CheckBoxBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxBackHover {
            get {
                object obj = ResourceManager.GetObject("CheckBoxBackHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxCross {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxCrossDisabled {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCrossDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxTick {
            get {
                object obj = ResourceManager.GetObject("CheckBoxTick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxTickDisabled {
            get {
                object obj = ResourceManager.GetObject("CheckBoxTickDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_R {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_R", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_RB {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_RB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_RI {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_RI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GDMSLogo {
            get {
                object obj = ResourceManager.GetObject("GDMSLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GDMSSplash {
            get {
                object obj = ResourceManager.GetObject("GDMSSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeButtonIcon {
            get {
                object obj = ResourceManager.GetObject("HomeButtonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeIcon {
            get {
                object obj = ResourceManager.GetObject("HomeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon icon32 {
            get {
                object obj = ResourceManager.GetObject("icon32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //record|level|quality
        ///records/items/enchants/a00000a_enchant.dbr|40|Magical
        ///records/items/enchants/a0000a_enchant.dbr|40|Magical
        ///records/items/enchants/a000a_enchant.dbr|40|Magical
        ///records/items/enchants/a00_blank.dbr|30|Magical
        ///records/items/enchants/a01a_enchant.dbr|40|Magical
        ///records/items/enchants/a02a_enchant.dbr|40|Magical
        ///records/items/enchants/a03a_enchant.dbr|40|Magical
        ///records/items/enchants/a04a_enchant.dbr|40|Magical
        ///records/items/enchants/a05a_enchant.dbr|40|Magical
        ///records/items/enc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string itemaffixes {
            get {
                return ResourceManager.GetString("itemaffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //record|width|height|level|class|quality|bitmap|setrecord
        ///records/creatures/npcs/npcgear/npc_child_girl_hair01.dbr|2|2|0|ArmorProtective_Head|Common|a01_head001.png|
        ///records/creatures/npcs/npcgear/npc_child_girl_hair02.dbr|2|2|0|ArmorProtective_Head|Common|a01_head001.png|
        ///records/creatures/npcs/npcgear/npc_child_girl_hair03.dbr|2|2|0|ArmorProtective_Head|Common|a01_head001.png|
        ///records/creatures/npcs/npcgear/npc_child_girl_hat01.dbr|2|2|0|ArmorProtective_Head|Common|a01_head001.png|
        ///records/creatures [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string iteminfos {
            get {
                return ResourceManager.GetString("iteminfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //record|setname|setitems
        ///records/items/lootsets/itemset_c001.dbr|tagItemSetC001Name|records/items/gearhead/c006_head.dbr;records/items/geartorso/c006_torso.dbr;records/items/gearshoulders/c004_shoulder.dbr;records/items/gearweapons/blunt1h/c004_blunt.dbr;records/items/gearweapons/shields/c003_shield.dbr
        ///records/items/lootsets/itemset_c001b.dbr|tagItemSetC001NameB|records/items/gearhead/c041_head.dbr;records/items/geartorso/c041_torso.dbr;records/items/gearshoulders/c027_shoulder.dbr;records/items/gearwea [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string itemsets {
            get {
                return ResourceManager.GetString("itemsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] itemtextures {
            get {
                object obj = ResourceManager.GetObject("itemtextures", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = Deutsch
        ///
        ///// messages
        ///msg_select_game_directory = Bitte zuerst Spielverzeichnis auswählen
        ///msg_game_directory_not_found = Spielverzeichnis nicht gefunden!
        ///msg_documents_directory_not_found = Dokumentenverzeichnis nicht gefunden!
        ///msg_update_available = Neue Version verfügbar: {0}\nJetzt aktualisieren?
        ///msg_confirm_closing = Grim Dawn läuft noch!\nDennoch schließen?
        ///msg_already_running = GDMultiStash läuft bereits!
        ///msg_game_already_running = Grim Dawn läuft bereits!
        ///msg_shortcut_created = Verknü [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_deDE {
            get {
                return ResourceManager.GetString("local_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = English (US)
        ///
        ///// messages
        ///msg_select_game_directory = Please first select your game directory
        ///msg_game_directory_not_found = Game directory not found!
        ///msg_documents_directory_not_found = Documents directory not found!
        ///msg_update_available = New version available: {0}\nUpdate now?
        ///msg_confirm_closing = Grim Dawn is still running\nClose anyway?
        ///msg_already_running = GDMultiStash is already running!
        ///msg_game_already_running = Grim Dawn is already running!
        ///msg_shortcut_created = Shortcut has be [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_enUS {
            get {
                return ResourceManager.GetString("local_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = 简体中文
        ///
        ///// messages
        ///msg_select_game_directory = Please first select your game directory
        ///msg_game_directory_not_found = 游戏目录未找到！
        ///msg_documents_directory_not_found = 文档目录未找到！
        ///msg_update_available = New version available: {0}\nUpdate now?
        ///msg_confirm_closing = Grim Dawn 仍在运行\n仍然关闭？
        ///msg_already_running = GDMultiStash 已经在运行！
        ///msg_game_already_running = 恐怖黎明已经在运行！
        ///msg_shortcut_created = 快捷方式已创建
        ///msg_invalid_transfer_file = 传输文件无效！
        ///msg_no_stash_selected = 没有选择存储！
        ///msg_backups_cleanedup = Backups cleane [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_zhCN {
            get {
                return ResourceManager.GetString("local_zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockBlackIcon {
            get {
                object obj = ResourceManager.GetObject("LockBlackIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockWhiteIcon {
            get {
                object obj = ResourceManager.GetObject("LockWhiteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallDown {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallOver {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallUp {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollAreaBottom {
            get {
                object obj = ResourceManager.GetObject("ScrollAreaBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollAreaMiddle {
            get {
                object obj = ResourceManager.GetObject("ScrollAreaMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollAreaTop {
            get {
                object obj = ResourceManager.GetObject("ScrollAreaTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollBar {
            get {
                object obj = ResourceManager.GetObject("ScrollBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollBarBottom {
            get {
                object obj = ResourceManager.GetObject("ScrollBarBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollBarTop {
            get {
                object obj = ResourceManager.GetObject("ScrollBarTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowBottom {
            get {
                object obj = ResourceManager.GetObject("ShadowBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowBottomLeft {
            get {
                object obj = ResourceManager.GetObject("ShadowBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowBottomRight {
            get {
                object obj = ResourceManager.GetObject("ShadowBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowLeft {
            get {
                object obj = ResourceManager.GetObject("ShadowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowMiddle {
            get {
                object obj = ResourceManager.GetObject("ShadowMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowRight {
            get {
                object obj = ResourceManager.GetObject("ShadowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowTop {
            get {
                object obj = ResourceManager.GetObject("ShadowTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowTopLeft {
            get {
                object obj = ResourceManager.GetObject("ShadowTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShadowTopRight {
            get {
                object obj = ResourceManager.GetObject("ShadowTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream soundButtonOverTick {
            get {
                return ResourceManager.GetStream("soundButtonOverTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBackground {
            get {
                object obj = ResourceManager.GetObject("StashListBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderB {
            get {
                object obj = ResourceManager.GetObject("StashListBorderB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderBL {
            get {
                object obj = ResourceManager.GetObject("StashListBorderBL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderBR {
            get {
                object obj = ResourceManager.GetObject("StashListBorderBR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderL {
            get {
                object obj = ResourceManager.GetObject("StashListBorderL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderR {
            get {
                object obj = ResourceManager.GetObject("StashListBorderR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderT {
            get {
                object obj = ResourceManager.GetObject("StashListBorderT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderTL {
            get {
                object obj = ResourceManager.GetObject("StashListBorderTL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StashListBorderTR {
            get {
                object obj = ResourceManager.GetObject("StashListBorderTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Gardistovo roucho
        ///tagItemSetC001NameB|Mírotvůrcovo roucho
        ///tagItemSetC002Name|Cestovatelův oděv
        ///tagItemSetC003Name|Maivenino útočiště
        ///tagItemSetC003NameB|Maivenina svatyně
        ///tagItemSetC004Name|Sláva krvavého žence
        ///tagItemSetC004NameB|Krveprolití krvavého žence
        ///tagItemSetC005Name|Záškodníkova spravedlnost
        ///tagItemSetC005NameB|Záškodníkův rozsudek
        ///tagItemSetC006Name|Klenoty císařského posla
        ///tagItemSetC006NameB|Značení císařského posla
        ///tagItemSetC007Name|Lékárník
        ///tagItemSetC007NameB| [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_CS_setnames {
            get {
                return ResourceManager.GetString("Text_CS_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Gardistenkleidung
        ///tagItemSetC001NameB|Kleidung des Friedensbewahrers
        ///tagItemSetC002Name|Forschergewand
        ///tagItemSetC003Name|Maivens Heiligtum
        ///tagItemSetC003NameB|Maivens Allerheiligstes
        ///tagItemSetC004Name|Ruhm des Blutschnitters
        ///tagItemSetC004NameB|Gemetzel des Blutschnitters
        ///tagItemSetC005Name|Gerechtigkeit des Marodeurs
        ///tagItemSetC005NameB|Urteil des Marodeurs
        ///tagItemSetC006Name|Ornat des Herolds
        ///tagItemSetC006NameB|Erkennungszeichen des Herolds
        ///tagItemSetC007Name|Der Apotheker [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_DE_setnames {
            get {
                return ResourceManager.GetString("Text_DE_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Guardsman&apos;s Raiment
        ///tagItemSetC001NameB|Peacekeeper&apos;s Raiment
        ///tagItemSetC002Name|Explorer&apos;s Garments
        ///tagItemSetC003Name|Maiven&apos;s Sanctuary
        ///tagItemSetC003NameB|Maiven&apos;s Sanctum
        ///tagItemSetC004Name|Bloodreaper&apos;s Glory
        ///tagItemSetC004NameB|Bloodreaper&apos;s Carnage
        ///tagItemSetC005Name|Marauder&apos;s Justice
        ///tagItemSetC005NameB|Marauder&apos;s Judgment
        ///tagItemSetC006Name|Herald&apos;s Regalia
        ///tagItemSetC006NameB|Herald&apos;s Markings
        ///tagItemSetC007Name|The Apothecary
        ///tagItemSetC007NameB|The Soothsayer
        ///ta [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_EN_setnames {
            get {
                return ResourceManager.GetString("Text_EN_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Atuendo del Centinela
        ///tagItemSetC001NameB|Atuendo del pacificador
        ///tagItemSetC002Name|Prendas del Explorador
        ///tagItemSetC003Name|Santuario de Maiven
        ///tagItemSetC003NameB|Santuario de Maiven
        ///tagItemSetC004Name|Gloria del Sanguinario
        ///tagItemSetC004NameB|Carnicería del Segador Sangriento
        ///tagItemSetC005Name|Justicia del Merodeador
        ///tagItemSetC005NameB|Juicio del Merodeador
        ///tagItemSetC006Name|Ropa de Gala del Heraldo
        ///tagItemSetC006NameB|Marcas del Heraldo
        ///tagItemSetC007Name|El Boticario [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_ES_setnames {
            get {
                return ResourceManager.GetString("Text_ES_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Vêtements de garde
        ///tagItemSetC001NameB|Habit de gardien de la paix
        ///tagItemSetC002Name|Vêtements d&apos;explorateur
        ///tagItemSetC003Name|Sanctuaire de Maiven
        ///tagItemSetC003NameB|Sanctuaire de Maiven
        ///tagItemSetC004Name|Gloire de la faucheuse ensanglantée
        ///tagItemSetC004NameB|Carnage de la Faucheuse ensanglantée
        ///tagItemSetC005Name|Justice du maraudeur
        ///tagItemSetC005NameB|Jugement du maraudeur
        ///tagItemSetC006Name|Régalia du Héraut
        ///tagItemSetC006NameB|Marquage du Héraut
        ///tagItemSetC007Name|L&apos; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_FR_setnames {
            get {
                return ResourceManager.GetString("Text_FR_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Uniforme della Guardia
        ///tagItemSetC001NameB|Armatura della Guardia
        ///tagItemSetC002Name|Abiti dell&apos;Esploratore
        ///tagItemSetC003Name|Santuario di Maiven
        ///tagItemSetC003NameB|Sanctorum di Maiven
        ///tagItemSetC004Name|Gloria del Mietitore di Sangue
        ///tagItemSetC004NameB|Massacro del Mietitore di Sangue
        ///tagItemSetC005Name|Giustizia del Predone
        ///tagItemSetC005NameB|Giudizio del Predone
        ///tagItemSetC006Name|Abiti Cerimoniali dell&apos;Araldo
        ///tagItemSetC006NameB|Insegne dell&apos;Araldo
        ///tagItemSetC007Name|Lo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_IT_setnames {
            get {
                return ResourceManager.GetString("Text_IT_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|ガーズマンの衣装
        ///tagItemSetC001NameB|ピースキーパーの衣装
        ///tagItemSetC002Name|探検家の衣服
        ///tagItemSetC003Name|メイヴェンの聖域
        ///tagItemSetC003NameB|メイヴェンの聖所
        ///tagItemSetC004Name|ブラッドリーパーの栄光
        ///tagItemSetC004NameB|ブラッドリーパーの殺戮
        ///tagItemSetC005Name|略奪者の正義
        ///tagItemSetC005NameB|略奪者の審判
        ///tagItemSetC006Name|伝令官の礼装
        ///tagItemSetC006NameB|伝令官の印
        ///tagItemSetC007Name|薬剤師
        ///tagItemSetC007NameB|占い師
        ///tagItemSetC008Name|破滅
        ///tagItemSetC008NameB|赦免
        ///tagItemSetC009Name|虚ろな目
        ///tagItemSetC010Name|鋭敏な射手の印
        ///tagItemSetC011Name|不浄の誓約
        ///tagItemSetC012Na [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_JA_setnames {
            get {
                return ResourceManager.GetString("Text_JA_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|근위병의 정복
        ///tagItemSetC001NameB|치안유지군의 정복
        ///tagItemSetC002Name|탐험가용 의복
        ///tagItemSetC003Name|메이븐의 안식처
        ///tagItemSetC003NameB|메이븐의 성역
        ///tagItemSetC004Name|피수확자의 영광
        ///tagItemSetC004NameB|피수확자의 학살
        ///tagItemSetC005Name|습격자의 심판
        ///tagItemSetC005NameB|습격자의 판결
        ///tagItemSetC006Name|전령관의 예복
        ///tagItemSetC006NameB|전령관의 상징들
        ///tagItemSetC007Name|약제사
        ///tagItemSetC007NameB|치료사
        ///tagItemSetC008Name|징벌
        ///tagItemSetC008NameB|단죄
        ///tagItemSetC009Name|초점없는 눈동자
        ///tagItemSetC010Name|샤프슈터의 상징
        ///tagItemSetC011Name|부정한 계약의 증표
        ///tagItemS [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_KO_setnames {
            get {
                return ResourceManager.GetString("Text_KO_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Ubiór Strażnika
        ///tagItemSetC001NameB|Szaty Rozjemcy
        ///tagItemSetC002Name|Wyposażenie Odkrywcy
        ///tagItemSetC003Name|Sanktuarium Maiveny
        ///tagItemSetC003NameB|Święte Miejsce Maiveny
        ///tagItemSetC004Name|Chwała Krwawego Żniwiarza
        ///tagItemSetC004NameB|Masakra Krwawego Żniwiarza
        ///tagItemSetC005Name|Sprawiedliwość Banity
        ///tagItemSetC005NameB|Osąd Banity
        ///tagItemSetC006Name|Insygnia Herolda
        ///tagItemSetC006NameB|Znaki Herolda
        ///tagItemSetC007Name|Aptekarz
        ///tagItemSetC007NameB|Uśmierzacz Bólu
        ///tagItemS [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_PL_setnames {
            get {
                return ResourceManager.GetString("Text_PL_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Indumentária do Soldado da Guarda
        ///tagItemSetC001NameB|Indumentária do Pacificador
        ///tagItemSetC002Name|Vestes do Explorador
        ///tagItemSetC003Name|Santuário de Maiven
        ///tagItemSetC003NameB|Sacrário de Maiven
        ///tagItemSetC004Name|Glória do Ceifador Sanguinário
        ///tagItemSetC004NameB|Carnificina do Ceifador Sanguinário
        ///tagItemSetC005Name|Justiça do Saqueador
        ///tagItemSetC005NameB|Julgamento do Saqueador
        ///tagItemSetC006Name|Paramentos do Arauto
        ///tagItemSetC006NameB|Marcas do Arauto
        ///tagItemSetC007N [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_PT_setnames {
            get {
                return ResourceManager.GetString("Text_PT_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|Đồng Phục Vệ Binh
        ///tagItemSetC001NameB|Đồng Phục Lính Bảo Vệ Hoà Bình
        ///tagItemSetC002Name|Trang Phục Nhà Thám Hiểm
        ///tagItemSetC003Name|Thánh Địa của Maiven
        ///tagItemSetC003NameB|Thánh Điện của Maiven
        ///tagItemSetC004Name|Vinh Quang của Kẻ Khát Máu
        ///tagItemSetC004NameB|Cuộc Tàn Sát của Kẻ Khát Máu
        ///tagItemSetC005Name|Công Lý của Kẻ Cướp Bóc
        ///tagItemSetC005NameB|Phát Quyết của Kẻ Cướp Bóc
        ///tagItemSetC006Name|Biểu Tượng của Sứ Giả
        ///tagItemSetC006NameB|Dấu Hiệu của Sứ Giả
        ///tagItemSetC007Name|Th [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_VI_setnames {
            get {
                return ResourceManager.GetString("Text_VI_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tagItemSetC001Name|帝国卫兵的戎装
        ///tagItemSetC001NameB|和平守护者的戎装
        ///tagItemSetC002Name|探险家的服饰
        ///tagItemSetC003Name|麦文的圣装
        ///tagItemSetC003NameB|麦文的圣衣
        ///tagItemSetC004Name|鲜血收割者的荣耀
        ///tagItemSetC004NameB|鲜血收割者的屠杀
        ///tagItemSetC005Name|掠夺者的正义
        ///tagItemSetC005NameB|掠夺者的审判
        ///tagItemSetC006Name|使者的华服
        ///tagItemSetC006NameB|使者的标记
        ///tagItemSetC007Name|药剂师
        ///tagItemSetC007NameB|预言者
        ///tagItemSetC008Name|破灭
        ///tagItemSetC008NameB|赦免
        ///tagItemSetC009Name|盲眼
        ///tagItemSetC010Name|神射手的徽记
        ///tagItemSetC011Name|不洁圣契
        ///tagItemSetC012Name|皇家的奢华
        ///tagItemSet [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Text_ZH_setnames {
            get {
                return ResourceManager.GetString("Text_ZH_setnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBackground {
            get {
                object obj = ResourceManager.GetObject("WindowBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBorderBottom {
            get {
                object obj = ResourceManager.GetObject("WindowBorderBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBorderBottomRight {
            get {
                object obj = ResourceManager.GetObject("WindowBorderBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBorderRight {
            get {
                object obj = ResourceManager.GetObject("WindowBorderRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBorderTop {
            get {
                object obj = ResourceManager.GetObject("WindowBorderTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowBorderTopRight {
            get {
                object obj = ResourceManager.GetObject("WindowBorderTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
