//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDMultiStash.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDMultiStash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseGray {
            get {
                object obj = ResourceManager.GetObject("buttonCloseGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseWhite {
            get {
                object obj = ResourceManager.GetObject("buttonCloseWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDropDownArrow {
            get {
                object obj = ResourceManager.GetObject("ButtonDropDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDropUpArrow {
            get {
                object obj = ResourceManager.GetObject("ButtonDropUpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLargeDown {
            get {
                object obj = ResourceManager.GetObject("ButtonLargeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLargeOver {
            get {
                object obj = ResourceManager.GetObject("ButtonLargeOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLargeUp {
            get {
                object obj = ResourceManager.GetObject("buttonLargeUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonMinimizeGray {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonMinimizeWhite {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallDown {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallOver {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSmallUp {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonTrayGray {
            get {
                object obj = ResourceManager.GetObject("buttonTrayGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonTrayWhite {
            get {
                object obj = ResourceManager.GetObject("buttonTrayWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxBack {
            get {
                object obj = ResourceManager.GetObject("CheckBoxBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxBackHover {
            get {
                object obj = ResourceManager.GetObject("CheckBoxBackHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxCross {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxCrossDisabled {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCrossDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxTick {
            get {
                object obj = ResourceManager.GetObject("CheckBoxTick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxTickDisabled {
            get {
                object obj = ResourceManager.GetObject("CheckBoxTickDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_R {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_R", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_RB {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_RB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] font_LinBiolinum_RI {
            get {
                object obj = ResourceManager.GetObject("font_LinBiolinum_RI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon icon32 {
            get {
                object obj = ResourceManager.GetObject("icon32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die records/creatures/npcs/npcgear/npc_child_girl_hair01:2:2
        ///records/creatures/npcs/npcgear/npc_child_girl_hair02:2:2
        ///records/creatures/npcs/npcgear/npc_child_girl_hair03:2:2
        ///records/creatures/npcs/npcgear/npc_child_girl_hat01:2:2
        ///records/creatures/npcs/npcgear/npc_feet_blacklegion01:2:2
        ///records/creatures/npcs/npcgear/npc_feet_blacklegion02:2:2
        ///records/creatures/npcs/npcgear/npc_feet_exile01:2:2
        ///records/creatures/npcs/npcgear/npc_feet_necromancer01:2:2
        ///records/creatures/npcs/npcgear/npc_feet_necromancer [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string itemsizes {
            get {
                return ResourceManager.GetString("itemsizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderB {
            get {
                object obj = ResourceManager.GetObject("listBorderB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderBL {
            get {
                object obj = ResourceManager.GetObject("listBorderBL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderBR {
            get {
                object obj = ResourceManager.GetObject("listBorderBR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderL {
            get {
                object obj = ResourceManager.GetObject("listBorderL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderR {
            get {
                object obj = ResourceManager.GetObject("listBorderR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderT {
            get {
                object obj = ResourceManager.GetObject("listBorderT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderTL {
            get {
                object obj = ResourceManager.GetObject("listBorderTL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap listBorderTR {
            get {
                object obj = ResourceManager.GetObject("listBorderTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = Deutsch
        ///
        ///// messages
        ///msg_select_game_directory = Bitte zuerst Spielverzeichnis auswählen
        ///msg_game_directory_not_found = Spielverzeichnis nicht gefunden!
        ///msg_documents_directory_not_found = Dokumentenverzeichnis nicht gefunden!
        ///msg_update_available = Neue Version verfügbar: {0}\nJetzt aktualisieren?
        ///msg_confirm_closing = Grim Dawn läuft noch!\nDennoch schließen?
        ///msg_already_running = GDMultiStash läuft bereits!
        ///msg_game_already_running = Grim Dawn läuft bereits!
        ///msg_shortcut_creat [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_deDE {
            get {
                return ResourceManager.GetString("local_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = English (GB)
        ///
        ///// messages
        ///msg_select_game_directory = Please first select your game directory
        ///msg_game_directory_not_found = Game directory not found!
        ///msg_documents_directory_not_found = Documents directory not found!
        ///msg_update_available = New version available: {0}\nUpdate now?
        ///msg_confirm_closing = Grim Dawn is still running\nClose anyway?
        ///msg_already_running = GDMultiStash is already running!
        ///msg_game_already_running = Grim Dawn is already running!
        ///msg_shortcut_created = Shor [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_enGB {
            get {
                return ResourceManager.GetString("local_enGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = English (US)
        ///
        ///// messages
        ///msg_select_game_directory = Please first select your game directory
        ///msg_game_directory_not_found = Game directory not found!
        ///msg_documents_directory_not_found = Documents directory not found!
        ///msg_update_available = New version available: {0}\nUpdate now?
        ///msg_confirm_closing = Grim Dawn is still running\nClose anyway?
        ///msg_already_running = GDMultiStash is already running!
        ///msg_game_already_running = Grim Dawn is already running!
        ///msg_shortcut_created = Shor [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_enUS {
            get {
                return ResourceManager.GetString("local_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///language_name = 简体中文
        ///
        ///// messages
        ///msg_select_game_directory = Please first select your game directory
        ///msg_game_directory_not_found = 游戏目录未找到！
        ///msg_documents_directory_not_found = 文档目录未找到！
        ///msg_update_available = New version available: {0}\nUpdate now?
        ///msg_confirm_closing = Grim Dawn 仍在运行\n仍然关闭？
        ///msg_already_running = GDMultiStash 已经在运行！
        ///msg_game_already_running = 恐怖黎明已经在运行！
        ///msg_shortcut_created = 快捷方式已创建
        ///msg_invalid_transfer_file = 传输文件无效！
        ///msg_no_stash_selected = 没有选择存储！
        ///msg_backups_cleanedup =  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string local_zhCN {
            get {
                return ResourceManager.GetString("local_zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockedBlack {
            get {
                object obj = ResourceManager.GetObject("lockedBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockedWhite {
            get {
                object obj = ResourceManager.GetObject("lockedWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marble {
            get {
                object obj = ResourceManager.GetObject("marble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio0 {
            get {
                object obj = ResourceManager.GetObject("radio0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio1 {
            get {
                object obj = ResourceManager.GetObject("radio1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallDown {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallOver {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReloadButtonSmallUp {
            get {
                object obj = ResourceManager.GetObject("ReloadButtonSmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollareaBottom {
            get {
                object obj = ResourceManager.GetObject("scrollareaBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollareaMiddle {
            get {
                object obj = ResourceManager.GetObject("scrollareaMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollareaTop {
            get {
                object obj = ResourceManager.GetObject("scrollareaTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollbar {
            get {
                object obj = ResourceManager.GetObject("scrollbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollbar_bottom {
            get {
                object obj = ResourceManager.GetObject("scrollbar_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrollbar_top {
            get {
                object obj = ResourceManager.GetObject("scrollbar_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowBottom {
            get {
                object obj = ResourceManager.GetObject("shadowBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowBottomLeft {
            get {
                object obj = ResourceManager.GetObject("shadowBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowBottomRight {
            get {
                object obj = ResourceManager.GetObject("shadowBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowLeft {
            get {
                object obj = ResourceManager.GetObject("shadowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowMiddle {
            get {
                object obj = ResourceManager.GetObject("shadowMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowRight {
            get {
                object obj = ResourceManager.GetObject("shadowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowTop {
            get {
                object obj = ResourceManager.GetObject("shadowTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowTopLeft {
            get {
                object obj = ResourceManager.GetObject("shadowTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadowTopRight {
            get {
                object obj = ResourceManager.GetObject("shadowTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream soundButtonOverTick {
            get {
                return ResourceManager.GetStream("soundButtonOverTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBackground {
            get {
                object obj = ResourceManager.GetObject("windowBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBorderBottom {
            get {
                object obj = ResourceManager.GetObject("windowBorderBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBorderBottomRight {
            get {
                object obj = ResourceManager.GetObject("windowBorderBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBorderRight {
            get {
                object obj = ResourceManager.GetObject("windowBorderRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBorderTop {
            get {
                object obj = ResourceManager.GetObject("windowBorderTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowBorderTopRight {
            get {
                object obj = ResourceManager.GetObject("windowBorderTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
